spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://chat-todo-rds.ctqmy268ia0k.ap-northeast-2.rds.amazonaws.com:3306/schedule?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: chateat1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE